DEFAULT_DEGRADATION_COST = 1.0
DEFAULT_DEGRADATION_PROBABILITY = 0.05
DEFAULT_MAX_BROKEN_PROB = 0.95

READY_STATE_NAME = "ready"
CONFIGURED_STATE_NAME = "configured"
EXECUTING_STATE_NAME = "executing"
BROKEN_STATE_NAME = "broken"
REPAIRING_STATE_NAME = "repairing"